### ISSUE TITLE
Question for the experiments of scored-based model on CIFAR-10 dataset.

### ISSUE THREAD

**Issue by mo666666** [IBM/VillanDiffusion#1]
Hello, ShenYen. VillanDiffusion is a solid and interesting work and I can't wait to run the code. However, would you mind sharing the  command about how to run the **scored-based model** on the CIFAR-10 dataset?  I notice that you only provide the script about the experiments of the scored-based model on the CELEBA-HQ dataset.

**Comment by mo666666** [comment]
Also find that the command for running LDM or Score-based model are the same. Does this mean that in the paper, the LDM and the Score-based model are the model?

**Comment by FrankCCCCC** [comment]
Hi, thank you for your interest. I've updated the command and uploaded all backdoored diffusion models on [HuggingFace](https://huggingface.co/newsyctw). Now you can run the experiment on CIFAR10 and Score-Based models.

**Comment by mo666666** [comment]
Thank you for your response. Can't wait to run your open-source code!

**Comment by FrankCCCCC** [comment]
Sorry for my fault, I backdoor [NCSN models](https://github.com/ermongroup/ncsn) as the representation of Score-based models. Note that because NCSN paper didn't release pre-trained NCSN models, I trained a new NCSN from scratch and backdoor it. Please download the pre-trained clean NCSN models from [HERE](https://huggingface.co/newsyctw/NCSN_CIFAR10_my).

**Comment by FrankCCCCC** [comment]
Let me know if you have any questions. Thank you again for your time.

**Comment by mo666666** [comment]
All my concerns have been addressed. Thank you again for your kind response and happy new year!
Best wishes
